// app/layout.tsx أو RootLayout.tsx
import './globals.css';
import { Roboto } from 'next/font/google';
import MainLayout from '@/src/components/Layout/MainLayout';

const roboto = Roboto({ subsets: ['latin'], weight: '700' });

export const metadata = {
	title: 'poultry',
	description: 'Generated by create next app',
	icons: {
		icon: '/image/poultry.png',
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang='en'
			className='dark'>
			<body
				className={`${roboto.className} bg-white dark:bg-darkprimary text-darkprimary dark:text-white`}>
				<MainLayout>{children}</MainLayout>
			</body>
		</html>
	);
}
